services:
  ormt-api:
    labels:
      - "traefik.http.routers.ormt-api.entrypoints=websecure"
      - "traefik.http.routers.ormt-api.tls=true"

    env_file:
      - ../services/postgres/env/.env.prod
      - ../services/keycloak/env/.env.prod
