server:
  port: 8093

starter:
  database:
    reset: false
    seed: false
  keycloak: 
    reset: false
    seed: false
  faker :
    seed : false
 
spring: 
  security:
    enabled: true
  datasource:
      url: jdbc:postgresql://localhost:5436/${spring.datasource.database} 
      driver-class-name: org.postgresql.Driver
      host: ormt-database
      port: 5432
      database: ormt
      username: ormt
      password: ormt@database
 
 


keycloak:
  host: localhost:8092
  auth-server-url: http://${keycloak.host}
  admin:
    realm: master
    client: admin-cli
    username: admin
    password: admin
  realm: ormt  # this is the realm name
  secret: "SSnam21521xFoFQAqi5TA68jKV3nBOyl"
  clients:
    backend:
      id: ormt-api   # this is the client id (name )of the api
      name: ormt api
      root-url: http://localhost:8093
      valid-redirect-urls: http://${keycloak.clients.backend.root-url}/*
      web-origins: "*"
      authorization: true
    frontend:
      id: ormt-web  # this is the client id (name) of the frontend
      name: ormt-ms
      root-url:  http://localhost:4200
      web-origins: "*"
      authorization: false

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.tool.hbm2ddl: ERROR
