server:
  port: 8093

starter:
  database:
    reset: true
    seed: true
  minio:
    reset: false
    seed: false
  keycloak: 
    reset: false
    seed: false
  faker :
    seed : false

 
spring: 
  security:
    enabled: true
  datasource:
      url: jdbc:postgresql://localhost:5436/${spring.datasource.database} 
      driver-class-name: org.postgresql.Driver
      host: ormt-database
      port: 5432
      database: ormt
      username: ormt
      password: ormt@database
 
flyway:
  enabled: true
  baseline-on-migrate: true
  baseline-description: "Dev Database State"
  locations: classpath:db/migration
  validate-on-migrate: true
  repair-on-validate: true
  out-of-order: true

minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: minio@ormt
  bucket: ormt
  allowed-origins: http://localhost:3000

keycloak:
  host: localhost:8092
  auth-server-url: http://${keycloak.host}
  admin:
    realm: master
    client: admin-cli
    username: admin
    password: admin
  realm: ormt  # this is the realm name
  secret: "SSnam21521xFoFQAqi5TA68jKV3nBOyl"
  clients:
    backend:
      id: ormt-api   # this is the client id (name )of the api
      name: ormt api
      root-url: http://localhost:8093
      valid-redirect-urls: http://${keycloak.clients.backend.root-url}/*
      web-origins: "*"
      authorization: true
    frontend:
      id: ormt-web  # this is the client id (name) of the frontend
      name: ormt-ms
      root-url:  http://localhost:3000
      web-origins: "*"
      authorization: false

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.tool.hbm2ddl: ERROR
