starter:
  database:
    reset: true
    seed: true
  keycloak: 
    reset: true
    seed: true
  faker :
    seed : false
 

spring:
  security:
    enabled: true
  datasource:
      url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
      driver-class-name: org.postgresql.Driver
      host: ormt-database
      port: 5432
      database: ormt
      username: ormt
      password: ormt@database2024
      
 
keycloak:
  host: ormt-kc:8080
  auth-server-url: http://${keycloak.host}
  admin:
    realm: master
    client: admin-cli
    username: admin
    password: admin
  realm: ormt  # this is the realm name
  secret: "SSnam21521xFoFQAqi5TA68jKV3nBOyl"
  clients:
    backend:
      id: ormt-api   # this is the client id (name )of the api
      name: ormt api
      root-url: http://ormt-api.ormt-ms.org
      valid-redirect-urls: http://${keycloak.clients.backend.root-url}/*
      web-origins: "http://ormt-api.ormt-ms.org"
      authorization: true
    frontend:
      id: ormt-web  # this is the client id (name) of the frontend
      name: ormt
      root-url:  https://www.ormt-ms.org
      web-origins: "https://www.ormt-ms.org"
      authorization: false
 
logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.tool.hbm2ddl: ERROR