spring:
  datasource:
    url: jdbc:tc:sqlserver:2019-CU4:///test-database
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: sa
    password: pva@database2024
  
  jpa: 
    hibernate:
      ddl-auto: create-drop
      database: sql_server
      database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    
  flyway:
    enabled: false
geoserver:
  url: http://localhost:8085/geoserver
  host: localhost
  port: 8085
  username: pva
  password: pva
  workspace: pva
  postgis-datastore: pva_postgis
   

  
 