spring:
  profiles:
    active: "@spring.profiles.active@"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false 
  sql:
    init:
      mode: never
  main:
    web-application-type: servlet
  output:
    ansi:
      enabled: ALWAYS
 
flyway:
  enabled: true
  baseline-on-migrate: true
  baseline-description: Initial database state
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}

data:
  external:
    data_path: ./data/
    level_1_path : ./data/pva/niveau_1/
    level_2_path : ./data/pva/niveau_2/

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
 
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html 
    filter: false
 
# logging:
#   level:
#     com.zaxxer.hikari: DEBUG
