starter:
  database:
    reset: true
    seed: true
  keycloak: 
    reset: true
    seed: true
  faker :
    seed : false
 

spring:
  security:
    enabled: true
  datasource:
      url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
      driver-class-name: org.postgresql.Driver
      host: ormt-database
      port: 5432
      database: ormt
      username: ormt
      password: ormt@database2024
      
 
keycloak:
  host: ormt-kc:8080
  auth-server-url: http://${keycloak.host}
  admin:
    realm: master
    client: admin-cli
    username: ormt
    password: ormt
  realm: ormt  # this is the realm name
  secret: "SSnam21521xFoFQAqi5TA68jKV3nBOyl"
  clients:
    backend:
      id: ormt-api   # this is the client id (name )of the api
      name: ormt api
      root-url: https://ormt-api.jemmal.net
      valid-redirect-urls: https://${keycloak.clients.backend.root-url}/*
      web-origins: "https://ormt-api.jemmal.net"
      authorization: true
    frontend:
      id: ormt-web  # this is the client id (name) of the frontend
      name: ormt
      root-url:  https://ormt.jemmal.net
      web-origins: "https://ormt.jemmal.net"
      authorization: false
 
logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.tool.hbm2ddl: ERROR