version: "3.9"
services:
  pva-geoserver:
    image: kartoza/geoserver:2.24.1
    container_name: pva-geoserver
    volumes:
      - "geoserver_data_pva_api:/opt/geoserver/data_dir"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pva-geoserver.entrypoints=web"
      - "traefik.http.routers.pva-geoserver.rule=Host(`${GEOSERVER_API_HOST_URL}`)"
      # - "traefik.http.services.pva-geoserver.loadbalancer.server.port=${GEOSERVER_API_PORT}"
    restart: on-failure
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_API_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_API_ADMIN_PASSWORD}
      # INIT_MEMORY: 2G
      # MAX_MEMORY: 3G
    networks:
      - proxy

volumes:
  geoserver_data_pva_api:

networks:
  proxy:
    external: true
