version: "3.9"

services:
  ormt-kc:
    command: start ##--import-realm
    labels:
      - "traefik.http.routers.ormt-kc.entrypoints=websecure"
      - "traefik.http.routers.ormt-kc.tls=true"
    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOST_URL}
