version: "3.9"
services:
  pva-database:
    build:
      context: .
      args:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: ${SQLSERVER_API_PASSWORD}
    container_name: ${PVA_DATABASE_HOSTNAME}
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: ${SQLSERVER_API_PASSWORD}
    networks:
      - proxy
    volumes:
      - "sqlserver_data_pva_api:/var/opt/mssql"

volumes:
  sqlserver_data_pva_api:

networks:
  proxy:
    external: true
