version: "3.9"
services:
  pva-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${PVA_DATABASE_HOSTNAME}
    restart: always
    environment:
      MSSQL_SA_PASSWORD: ${SQLSERVER_API_PASSWORD}
      SQLSERVER_DB: ${SQLSERVER_API_DB}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    volumes:
      - "sqlserver_data_pva_api:/var/opt/mssql"
    networks:
      - proxy

volumes:
  sqlserver_data_pva_api:

networks:
  proxy:
    external: true
