version: "3.9"
services:
  pva-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${PVA_DATABASE_HOSTNAME}
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: ${SQLSERVER_API_PASSWORD}
    volumes:
      - "sqlserver_data_pva_api:/var/opt/mssql"
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

    networks:
      - proxy
    user: root # Ensure the script runs with the necessary permissions
    command: /bin/bash /docker-entrypoint-initdb.d/init-db.sh & /opt/mssql/bin/sqlservr

volumes:
  sqlserver_data_pva_api:

networks:
  proxy:
    external: true
