version: "3.9"

services:
  minio-ormt:
    restart: on-failure
    ports:
      - "9000:9000" # Minio API
      - "9001:9001" # Minio Console
    labels:
      - "traefik.http.routers.minio-api.entrypoints=web"
      - "traefik.http.routers.minio-api.tls=false"
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.routers.minio-console.tls=false"
    environment:
      # HTTP URLs for stage environment
      MINIO_BROWSER_REDIRECT_URL: http://${MINIO_HOST_URL}:9001
      MINIO_SERVER_URL: http://${MINIO_HOST_URL}:9000
    deploy:
      resources:
        limits:
          memory: 1G
