services:
  minio-ormt:
    restart: unless-stopped
    labels:
      # Update to use secure connections
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls=true"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
