ALTER TABLE chiffre_cle
    ADD COLUMN IF NOT EXISTS mode_source VARCHAR(50) NOT NULL DEFAULT 'MANUAL',
    ADD COLUMN IF NOT EXISTS format_type VARCHAR(50) NOT NULL DEFAULT 'NUMBER',
    ADD COLUMN IF NOT EXISTS prefix_label VARCHAR(255),
    ADD COLUMN IF NOT EXISTS suffix_label VARCHAR(255),
    ADD COLUMN IF NOT EXISTS evolution_mode VARCHAR(50) NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS metadata_json TEXT,
    ADD COLUMN IF NOT EXISTS style_json TEXT;
